config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'home#index'

  resources :home, only: [:index]
  resources :search, only: [:index]
  resources :hosts

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/host.rb
class Host < ActiveRecord::Base
  serialize :parse_url

  belongs_to :province
  has_many :rooms
  has_many :schedules

  scope :reservable, -> (checkin, checkout, guest) {
    eager_load(:schedules, :rooms)
      .where("rooms.guest >= #{guest}")
      .where("schedules.year >= #{checkin.year} AND schedules.year <= #{checkin.year}")
      .where("schedules.month >= #{checkin.month} AND schedules.month <= #{checkout.month}")
      .where("schedules.day >= #{checkin.day} AND schedules.day < #{checkout.day}")
      .where(schedules: { reserved: false})
  }

end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :hosts
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :host
  has_many :schedules

  scope :reservable, -> (checkin, checkout, guest) {
    eager_load(:schedules)
      .where("rooms.guest >= #{guest}")
      .where("schedules.year >= #{checkin.year} AND schedules.year <= #{checkin.year}")
      .where("schedules.month >= #{checkin.month} AND schedules.month <= #{checkout.month}")
      .where("schedules.day >= #{checkin.day} AND schedules.day < #{checkout.day}")
      .where(schedules: { reserved: false})
  }

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :host
  belongs_to :room

  scope :reservable, -> (checkin, checkout, guest) {
    eager_load(:host, :room)
      .where("year >= #{checkin.year} AND year <= #{checkin.year}")
      .where("month >= #{checkin.month} AND month <= #{checkout.month}")
      .where("day >= #{checkin.day} AND day < #{checkout.day}")
      .where(reserved: false)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recommend_hosts = Host.limit 6
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController

  def index
    @hosts = Host.all
  end

  def show
    @checkin = params.fetch(:checkin, nil)
    @checkout = params.fetch(:checkout, nil)
    @guest = params.fetch(:guest, nil).to_i

    @host = Host.find(params[:id])

    @rooms = Room.where(host: @host)
    @rooms = if @checkin.present? && @checkout.present?
                  checkin = @checkin.to_date
                  checkout = @checkout.to_date
                  @rooms.reservable(checkin, checkout, @guest)
                end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @checkin = params.fetch(:checkin, nil)
    @checkout = params.fetch(:checkout, nil)
    @guest = params.fetch(:guest, nil).to_i

    @hosts = if @checkin.nil? || @checkout.nil?
               []
             else
               checkin = @checkin.to_date
               checkout = @checkout.to_date
               Host.reservable(checkin, checkout, @guest)
             end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_host.slim
.col-md-4.col-sm-6.margin-btm-20
  .news-sec
    .news-thumnail
      a href=host_path(host.id)
        img.img-responsive src=image_path('work-1.jpg')
    .news-desc
      h3.blog-post-title
        a.hover-color href=host_path(host.id) = host.name
      span.news-post-cat = "#{host.address}| #{time_ago_in_words(host.updated_at)}"
      p

app/views/home/_recommend_hosts.slim
.row
  = render partial: "host", collection: @recommend_hosts

app/views/home/_search_form.slim
= form_tag search_index_path, method: :get, class: "search-form"

  /.form-group.col-xs-12
    input.form-control name=:place type="text" placeholder=t("search.where_do_you_want_to_go")

  .addtional-search-form
    .input-daterange
      .form-group.col-sm-4.col-xs-6
        input#checkin.datepicker.form-control name=:checkin type="text" placeholder=t("common.checkin") value=params[:checkin]
      .form-group.col-sm-4.col-xs-6
        input#checkout.datepicker.form-control name=:checkout type="text" placeholder=t("common.checkin") value=params[:checkout]

    .form-group.col-sm-4.col-xs-12
      select.form-control name=:guest
        - (1..16).to_a.each do |count|
          - selected = (count == params[:guest].to_i ? true : false)
          - if count == 1
            option value=count selected=selected = t("search.guest", count: count)
          - else
            option value=count selected=selected = t("search.guests", count: count)

    .col-xs-12
      button type="submit" class="btn btn-lg btn-block theme-btn-color" = t("search.find_a_place")

app/views/home/index.slim
- content_for :top_section do
  section.padding-40.page-tree-bg
    .container
      h3.page-tree-text = t("home.welcome_title")
      h4.text-center = t("home.welcome_sub_title")
      = render 'search_form'

.text-center
  h2 GOGOGO
  p rest
  .space-20

= render 'recommend_hosts'

app/views/hosts/_room.slim
= link_to "#", class: 'col-sm-6 col-xs-12 list-group-item' do
  h5.list-group-item-heading = room.name
  p.list-group-item-text = ""

app/views/hosts/index.html.erb
<%= react_component 'Hosts', { data: @hosts } %>

app/views/hosts/show.slim
.page-header
  h2 = @host.name

#room-list.list-group
  = render partial: "room", collection: @rooms

app/views/layouts/_header.slim
header.header-main
  .navbar.navbar-default.sticky-nav.sticky role="navigation"
    .container
      .navbar-header
        button type="button" class="navbar-toggle" data-toggle="collapse"
          .sr-only  Toggle navigation
          .icon-bar
          .icon-bar
          .icon-bar
        .navbar-brand href="index.html"
          = "Hugar"

      .navbar-collapse.collapse
        ul.nav.navbar-nav.navbar-right
          li
            a.js-activated href="#" 회원가입
          li
            a.js-activated href="#" 로그인
          li.dropdown
            a.dropdown-toggle.js-activated href="#" 도움말
            /ul.dropdown-menu
              li
                a href="#" D1
                a href="#" D2
          li
            a.js-activated href="#" 연락하기

app/views/layouts/_search_form.slim
= form_tag search_index_path, method: :get

  /.form-group.col-xs-12
    input.form-control name=:place type="text" placeholder=t("search.where_do_you_want_to_go")

  .addtional-search-form
    .input-daterange
      .form-group.col-sm-4.col-xs-6
        input#checkin.datepicker.form-control name=:checkin type="text" placeholder=t("common.checkin") value=params[:checkin]
      .form-group.col-sm-4.col-xs-6
        input#checkout.datepicker.form-control name=:checkout type="text" placeholder=t("common.checkin") value=params[:checkout]

    .form-group.col-sm-4.col-xs-12
      select.form-control name=:guest
        - (1..16).to_a.each do |count|
          - selected = (count == params[:guest].to_i ? true : false)
          - if count == 1
            option value=count selected=selected = t("search.guest", count: count)
          - else
            option value=count selected=selected = t("search.guests", count: count)

    .col-xs-12
      button type="submit" class="btn btn-primary btn-block" = t("search.find_a_place")

app/views/layouts/application.slim
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui"
    meta content="휴양림 찾기" name="description"
    meta content="휴양림, 검색, 펜션, 전국, 휴양림검색, Airbnb, 에어비앤비" name="keyword"
    meta name="apple-mobile-web-app-capable" content="yes"

    meta content="#da532c" name="msapplication-TileColor"

    = content_for?(:meta) ? yield(:meta) : (render 'layouts/meta')
    title= content_for?(:title) ? yield(:title) : "휴가(Hugar)"


    link href="http://fonts.googleapis.com/css?family=Raleway:400,300,100,700,800,500" rel="stylesheet" type="text/css"
    link href="http://fonts.googleapis.com/css?family=Playfair+Display:400italic" rel="stylesheet" type="text/css"
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>]

    = stylesheet_link_tag 'application'
    = yield :page_specific_stylesheets

    = javascript_include_tag 'application'
    = yield :page_specific_head_scripts

    = csrf_meta_tags

  body
    = render "layouts/header"

    = content_for?(:top_section) ? yield(:top_section) : nil

    .space-70
    .container
      .row
        .col-md-12
          = content_for?(:contents) ? yield(:contents) : yield

app/views/search/_host.slim
= link_to host_path(host.id, checkin: @checkin, checkout: @checkout, guest: @guest), class: 'col-sm-6 col-xs-12 list-group-item' do
  h5.list-group-item-heading = host.name
  p.list-group-item-text
    = host.updated_at.strftime("%Y/%m/%d")

app/views/search/index.slim
.row

#host-list.list-group
  = render partial: "host", collection: @hosts